Repository mikeharrison57/rancid-tomatillos, pull requests merged in 2022-07, with the labels that each got.

#4 Iteration 1 displaying movies
  src/App.js
  src/MovieCard.css
  src/MovieCard.js
  src/MovieContainer.css
  src/MovieContainer.js
  src/Navbar.js
  src/index.css
  src/index.js
  src/mock-movie-data.js
Labels: enhancement

#5 Feature/iteration 2 display individual movie
  src/App.js
  src/IndividualMovie.css
  src/IndividualMovie.js
  src/MovieCard.js
  src/MovieContainer.js
  src/Navbar.css
  src/Navbar.js
  src/mock-individual-data.js
Labels: enhancement

#6 Feat/iteration 3 network requests/async js
  cypress.config.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/individual1.json
  cypress/fixtures/movies.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/App.js
  src/IndividualMovie.js
  src/MovieCard.js
  src/MovieContainer.js
  src/Navbar.css
  src/Navbar.js
  src/index.css
  src/mock-individual-data.js
Labels: enhancement

#12 Feat/cypress testing and refactoring
  cypress/e2e/allmovies.cy.js
  cypress/e2e/individualmovie.cy.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/allmovies.json
  cypress/fixtures/individualmovie1.json
  src/App.css
  src/components/IndividualMovie.js
  src/components/Navbar.js
Labels: enhancement, testing

#14 feat: deployed page and refactored tagline
  public/index.html
  src/components/IndividualMovie.js
Labels: enhancement

#15 Feat/trailer disply
  cypress/e2e/allmovies.cy.js
  cypress/e2e/individualmovie.cy.js
  cypress/fixtures/individualmovie1.json
  cypress/fixtures/individualmovie2.json
  src/apiCalls.js
  src/assets/play-trailer-button.png
  src/components/IndividualMovie.js
  src/components/MovieContainer.js
  src/components/Trailer.js
  src/styles/IndividualMovie.css
  src/styles/Trailer.css
Labels: enhancement, testing

#16 docs: add README.md draft
  README.md
Labels: documentation

#17 Refactor/final refactor
  cypress/e2e/allmovies.cy.js
  cypress/e2e/individualmovie.cy.js
  src/App.js
  src/components/IndividualMovie.js
  src/components/MovieContainer.js
  src/components/Navbar.js
  src/components/Trailer.js
  src/index.css
  src/styles/IndividualMovie.css
  src/styles/Navbar.css
Labels: refactor
